### ISSUE TITLE
Cant add lists (tokio-runtime-worker panicked)

### ISSUE THREAD

**Issue by 9acca9** [megadrive/stremio-letterboxd#36]
Hi.
Im the one that ask you in reddit about selfhosting.
(probably a lot of people, but maybe im the last one).

Well, i try to install. And use sqlite. Change the .env, etc.
Im getting this error when try to add any list:

```
Stremio-Letterboxd available at http://localhost:3030
Movies That Will Make You Say “What the Fuck” At Least 3 Times
Got config: /zanderific/list/movies-that-will-make-you-say-what-the-fuck/ (list) with 2 options from %2Fzanderific%2Flist%2Fmovies-that-will-make-you-say-what-the-fuck%2F%7Ccn%3DMovies%20That%20Will%20Make%20You%20Say%20%E2%80%9CWhat%20the%20Fuck%E2%80%9D%20At%20Least%203%20Times
thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:178:18:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:178:18:
internal error: entered unreachable code
```
Thanks!

**Comment by megadrive** [comment]
I know you've closed this but the only thing built in rust (and using Tokio) is prisma. I would suggest running clean.js and reinstalling your dependencies with npm.
